AddressLine1: IBX LD8 6/7/8/9 Harbour 6/7 Harbour Exchange Square
AddressLine2: 
City: London
Country: United Kingdom
Description: ESnet - London
ID: 10365
Latitude: 51.49806950
LongName: Energy Sciences Network - London
Longitude: -0.01436050
State: Limeharbour
Zipcode: '60439'
