AddressLine1: 637 Colleg Ave
City: Lancaster 
Country: United States
ID: 10335
Latitude: 40.0479
LongName: Franlin and Marshall College Research and Computing Services - ITS
Longitude: -76.3202
State: PA
Zipcode: '17603'
