AddressLine1: Science Park 610
City: Amsterdam
Country: Netherlands
Description: ESnet- Amsterdam
ID: 10364
Latitude: 52.35467570
LongName:  Energy Sciences Network - Amsterdam
Longitude: 4.95911940
State: XH
Zipcode: 'AM3:01:031101'
