LongName: SURF Amsterdam MS4 services
Description: The ICT cooperative of teaching and research in the Netherlands
ID: 10348
AddressLine1: Science Park 140
City: Amsterdam
Country: Netherlands
Latitude: 52.356730
Longitude: 4.954590
