LongName: National Center for High-performance Computing
Description: National Center for High-performance Computing, National Applied Research Laboratories
ID: 10359
City: Hsinchu
Country: Taiwan
Latitude: 24.783
Longitude: 120.996
