LongName: FIU HPC Division of Information Technology
Description: FIU Panther cluster sponsored by campus central IT division.
AddressLine1: 11200 SW 8th St
AddressLine2: PC415b
City: Miami
Country: United States
ID: 10355
Latitude: 25.757
Longitude: -80.374
State: FL
Zipcode: '33199'

