LongName: University of Arkansas at Little Rock
Description: UA Little Rock IT Services Cluster
ID: 10347
AddressLine1: 2801 South University Ave
AddressLine2: Building Trojan B Room 205
City: Little Rock
Country: United States
State: Arkansas
Zipcode: "72204"
Latitude: 34.72265
Longitude: -92.33989
