LongName: Scientific Computing and Imaging Institute Virtual Data Collaboratory
Description: >
  University of Utah's Scientific Computing and Imaging Institute
  (SCI) located in Salt Lake City. Test site for the Virtual Data
  Collaboratory (VDC) initiative.
ID: 10348
AddressLine1: 72 S Central Campus Drive, Room 3750
City: Salt Lake City
Country: United States
State: UT
Zipcode: '84112'
Latitude: 40.7608
Longitude: -111.891
