---
LongName: >-
  India-based Neutrino Observatory (INO) at Tata Institute of
  Fundamental Research (TIFR)
Description: 'INO Simulation Cluster at TIFR, with OSG-CE and SE'
ID: 10361

AddressLine1: Dr Homi Bhabha Road, Colaba
City: Mumbai
Country: India

Latitude: 18.90757
Longitude: 72.80802
